In [77]:
import geopandas as gpd
import pandas as pd
from pathlib import Path

In [11]:
gdf = gpd.read_file("/mnt/store-lidarhd/projet-LHD/IA/BDForet/Data/PureForestID/metadata/PureForestID-patches.gpkg")
gdf = gdf[gdf.split.isin(["test","val"])]
gdf = gdf[["split", "patch_num", "bdforet_identifier","bdforet_cat_code", "bdforet_cat_name","inventory_species_label", ]]
print(gdf.columns)
gdf.head()

Index(['split', 'patch_num', 'bdforet_identifier', 'bdforet_cat_code',
       'bdforet_cat_name', 'inventory_species_label'],
      dtype='object')

,split,patch_num,bdforet_identifier,bdforet_cat_code,bdforet_cat_name,inventory_species_label
0,val,00035_00000,FORESTIE0000000000100093,FF1-14-14,Forêt fermée de robinier pur,14
1,val,00035_00001,FORESTIE0000000000100093,FF1-14-14,Forêt fermée de robinier pur,14
2,val,00035_00002,FORESTIE0000000000100093,FF1-14-14,Forêt fermée de robinier pur,14
3,val,00035_00003,FORESTIE0000000000100093,FF1-14-14,Forêt fermée de robinier pur,14
4,val,00035_00004,FORESTIE0000000000100093,FF1-14-14,Forêt fermée de robinier pur,14

In [79]:
PREDICTIONS_FOLDER = Path("/mnt/store-lidarhd/projet-LHD/IA/MYRIA3D-SHARED-WORKSPACE/CGaydon/runs/2023-11-03/17-46-48/")
PREDICTIONS_FILE = PREDICTIONS_FOLDER / "predictions.csv"
df = pd.read_csv(PREDICTIONS_FILE)
# df["patch_id"] = df["patch_id"].apply(lambda patch_id: patch_id + "_BDF_IF")
df.head(n=10) # duplicates !
df = df.drop_duplicates("patch_id",keep="first")
# df.head()

In [80]:
merge = gdf.merge(df, left_on="patch_num", right_on="patch_id", how="inner")
# merge["OK"] = (merge["preds"] == merge["targets"]).astype(int)
# merge["NOK"] = (merge["preds"] != merge["targets"]).astype(int)
print(len(merge))
# merge.head()

22428

In [81]:
groups = merge.groupby(["bdforet_identifier","bdforet_cat_code","targets","preds"]).size().reset_index()
pivot = groups.pivot(index=["bdforet_identifier","targets"],columns="preds",values=0).fillna(0).astype(int)
pivot["consensus"] = pivot.idxmax(axis=1)
pivot = pivot.reset_index()
pivot["accurate"] = pivot["consensus"] == pivot["targets"]
pivot.to_csv(PREDICTIONS_FOLDER/"predictions-pivot-by-polygon.csv")
pivot

preds,bdforet_identifier,targets,0,1,2,3,4,6,7,8,9,10,11,consensus,accurate
0,FORESTIE0000000000403437,0,0,0,10,58,0,2,0,30,0,3,0,3,False
1,FORESTIE0000000000410030,8,0,0,0,0,0,0,0,280,0,0,0,8,True
2,FORESTIE0000000000600707,3,6,82,1095,1281,124,386,47,0,0,3,0,3,True
3,FORESTIE0000000000622465,6,12,2,1,13,9,591,440,22,3,34,1,6,True
4,FORESTIE0000000001316805,7,0,0,0,0,0,0,405,0,0,0,0,7,True
5,FORESTIE0000000001319907,7,0,0,0,0,0,0,19,0,0,0,0,7,True
6,FORESTIE0000000001504926,3,0,0,0,36,0,0,0,0,0,0,0,3,True
7,FORESTIE0000000001505158,0,503,34,0,7,0,0,0,0,0,0,0,0,True
8,FORESTIE0000000001919642,11,0,0,0,1,0,0,0,0,6,3,109,11,True
9,FORESTIE0000000002323832,9,0,1,0,1,0,0,0,0,39,0,0,9,True
10,FORESTIE0000000002436133,2,0,0,7,1,0,0,0,0,0,0,0,2,True
11,FORESTIE0000000002448837,9,0,11,3,0,0,0,17,0,82,0,0,9,True
12,FORESTIE0000000002450560,9,0,8,0,0,0,0,0,0,118,8,0,9,True
13,FORESTIE0000000002451015,9,0,4,0,0,0,0,0,0,22,1,0,9,True
14,FORESTIE0000000002600118,10,0,0,0,8,0,137,0,0,0,525,22,10,True
15,FORESTIE0000000003008593,4,0,13,0,34,348,1,1,0,2,0,0,4,True
16,FORESTIE0000000003009825,4,0,5,0,0,802,4,0,0,0,0,0,4,True
17,FORESTIE0000000003215110,3,0,0,45,282,0,0,0,0,0,0,0,3,True
18,FORESTIE0000000003412021,4,0,0,0,40,568,0,0,0,0,0,0,4,True
19,FORESTIE0000000003807482,1,0,0,8,0,0,0,0,0,0,0,0,2,False
20,FORESTIE0000000003807658,2,0,0,47,0,0,0,0,0,0,0,0,2,True
21,FORESTIE0000000003807667,2,0,0,35,0,0,0,0,0,0,0,0,2,True
22,FORESTIE0000000003807669,2,0,0,13,0,0,0,0,0,0,0,0,2,True
23,FORESTIE0000000003807691,2,0,0,61,0,0,0,0,0,0,0,0,2,True
24,FORESTIE0000000003807731,2,0,0,142,0,0,0,0,0,0,0,0,2,True
25,FORESTIE0000000003809798,3,0,0,1,0,0,0,0,0,0,0,0,2,False
26,FORESTIE0000000004302294,0,40,0,10,49,0,1,0,0,0,0,0,3,False
27,FORESTIE0000000004310883,11,1,0,0,0,0,0,0,1,0,0,812,11,True
28,FORESTIE0000000004311101,11,0,0,0,0,0,0,0,0,0,0,12,11,True
29,FORESTIE0000000004608561,3,1,2,121,5228,0,0,0,0,2,0,5,3,True
30,FORESTIE0000000004609242,1,0,0,0,38,0,0,0,0,0,0,0,3,False
31,FORESTIE0000000004613341,3,0,0,11,197,0,0,0,0,0,0,0,3,True
32,FORESTIE0000000004710749,2,0,0,0,1,0,0,0,0,0,0,0,3,False
33,FORESTIE0000000004805186,1,8,115,0,4,49,0,0,0,0,5,0,1,True
34,FORESTIE0000000004807370,6,0,0,0,0,0,1,0,0,0,0,0,6,True
35,FORESTIE0000000004809393,6,0,0,0,0,0,56,0,0,0,6,0,6,True
36,FORESTIE0000000004812131,6,0,0,0,0,0,21,0,0,0,0,0,6,True
37,FORESTIE0000000004814009,10,0,0,0,0,0,6,0,0,0,11,0,10,True
38,FORESTIE0000000004814638,11,0,1,0,0,0,5,0,0,7,0,13,11,True
39,FORESTIE0000000004835292,10,0,13,10,13,0,201,0,0,77,1014,50,10,True
40,FORESTIE0000000006906715,9,2,0,5,0,0,0,0,0,42,0,33,9,True
41,FORESTIE0000000008208311,2,0,0,13,0,0,0,0,0,0,0,0,2,True
42,FORESTIE0000000008208336,2,0,0,38,0,0,0,0,0,0,0,0,2,True
43,FORESTIE0000000008208343,2,0,0,17,0,0,0,0,0,0,0,0,2,True
44,FORESTIE0000000008208450,2,0,0,4,0,0,0,0,0,0,0,0,2,True
45,FORESTIE0000000008208460,2,0,0,6,0,0,0,0,0,0,0,0,2,True
46,FORESTIE0000000008210212,3,2,0,3376,1537,0,5,0,1,1,3,0,2,False

In [83]:
synthesis = pivot.groupby("targets").agg({"accurate":"mean","bdforet_identifier":"size"}).round(2)
synthesis.to_csv(PREDICTIONS_FOLDER/"predictions-accuracy-by-class.csv")
synthesis

preds    accurate  bdforet_identifier
targets
0            0.33                   3
1            0.33                   3
2            0.92                  12
3            0.71                   7
4            1.00                   3
6            1.00                   4
7            1.00                   2
8            1.00                   1
9            1.00                   5
10           1.00                   3
11           1.00                   4